apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - rbac.yaml
  - source.yaml
  - monitoring.yaml
  - admission.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: infra
